### ISSUE TITLE
Compatibility other TI 

### ISSUE THREAD

**Issue by d82k** [chromalock/TI-32#5]
Hello,
This is indeed cool, I have an old TI-89 (first model) would that work as well?

**Comment by Log4Jake** [comment]
Most of the calculator code is in basic which can run on almost any TI. I would look at the programming differences between the two you can ask about the differences on [cemetech.net](cemetech.net) keep in mind the pcb might need to be tweaked for this calculator. There is no guaranteed support.

**Comment by Nathan5471** [comment]
Would this work with a normal TI-84 plus?

**Comment by chromalock** [comment]
@d82k it may require changes to the BASIC, since there are minor differences between the 84 and the 89 IIRC.
@Nathan5471 Im pretty sure the silver just adds speed, so probably?

**Comment by Log4Jake** [comment]
@Nathan5471 I believe so yes
