### ISSUE TITLE
please make for ti 84 plus python 

### ISSUE THREAD

**Issue by stelle-hsr** [chromalock/TI-32#6]
i would love to be able to use this on mine

**Comment by BrainwashAlpha** [comment]
bro the 84 python edition has restrictions on C and ASM program usage. TI disabled the ability to run them without jailbreak or workarounds. It might be tough, but if you can get around that fact , they have the same ez80 processors as all 84 calcs afaik just a faster clock speed

**Comment by TIny-Hacker** [comment]
TI eZ80 models lack the I/O port necessary for this project, unlike the older Z80 based monochrome calculators and TI-84 Plus CSE.

**Comment by Log4Jake** [comment]
Thanks @TIny-Hacker that was going to be my exact answer.

**Comment by BrainwashAlpha** [comment]
I will also add that, if you want compatability on the eZ80 programs you would probably have to adapt the I/O port functionality to the USB port instead
