### ISSUE TITLE
No I/O Port

### ISSUE THREAD

**Issue by Nathan5471** [chromalock/TI-32#8]
My Ti-84 Plus didn't come with a I/O Port, but I still see the slot for it. Would this mod still work if I soldered it to the empty slot?
![20240917_1742462](https://github.com/user-attachments/assets/ac211a80-bcea-4a89-8903-60567ed0ca47)

**Comment by Log4Jake** [comment]
Yes, those pads are still connected should work fine.

**Comment by Log4Jake** [comment]
This issue can be closed.

**Comment by Nathan5471** [comment]
Ok, thanks for the help
